var myInfo = [
  {
  "login": "kpittner",
  "id": 12478022,
  "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kpittner",
  "html_url": "https://github.com/kpittner",
  "followers_url": "https://api.github.com/users/kpittner/followers",
  "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
  "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
  "organizations_url": "https://api.github.com/users/kpittner/orgs",
  "repos_url": "https://api.github.com/users/kpittner/repos",
  "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
  "received_events_url": "https://api.github.com/users/kpittner/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Kelsey Pittner",
  "company": "",
  "blog": "",
  "location": "",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 9,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2015-05-16T23:19:07Z",
  "updated_at": "2015-06-02T17:14:10Z"
}
];

var myDemos = [
  {
    "id": 35947930,
    "name": "firstDemo",
    "full_name": "kpittner/firstDemo",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/firstDemo",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/firstDemo",
    "forks_url": "https://api.github.com/repos/kpittner/firstDemo/forks",
    "keys_url": "https://api.github.com/repos/kpittner/firstDemo/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/firstDemo/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/firstDemo/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/firstDemo/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/firstDemo/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/firstDemo/events",
    "assignees_url": "https://api.github.com/repos/kpittner/firstDemo/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/firstDemo/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/firstDemo/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/firstDemo/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/firstDemo/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/firstDemo/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/firstDemo/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/firstDemo/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/firstDemo/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/firstDemo/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/firstDemo/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/firstDemo/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/firstDemo/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/firstDemo/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/firstDemo/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/firstDemo/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/firstDemo/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/firstDemo/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/firstDemo/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/firstDemo/merges",
    "archive_url": "https://api.github.com/repos/kpittner/firstDemo/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/firstDemo/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/firstDemo/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/firstDemo/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/firstDemo/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/firstDemo/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/firstDemo/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/firstDemo/releases{/id}",
    "created_at": "2015-05-20T12:58:53Z",
    "updated_at": "2015-05-20T12:59:52Z",
    "pushed_at": "2015-05-20T12:59:09Z",
    "git_url": "git://github.com/kpittner/firstDemo.git",
    "ssh_url": "git@github.com:kpittner/firstDemo.git",
    "clone_url": "https://github.com/kpittner/firstDemo.git",
    "svn_url": "https://github.com/kpittner/firstDemo",
    "homepage": "",
    "size": 100,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 35948140,
    "name": "homeworkOne",
    "full_name": "kpittner/homeworkOne",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/homeworkOne",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/homeworkOne",
    "forks_url": "https://api.github.com/repos/kpittner/homeworkOne/forks",
    "keys_url": "https://api.github.com/repos/kpittner/homeworkOne/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/homeworkOne/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/homeworkOne/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/homeworkOne/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/homeworkOne/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/homeworkOne/events",
    "assignees_url": "https://api.github.com/repos/kpittner/homeworkOne/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/homeworkOne/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/homeworkOne/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/homeworkOne/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/homeworkOne/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/homeworkOne/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/homeworkOne/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/homeworkOne/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/homeworkOne/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/homeworkOne/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/homeworkOne/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/homeworkOne/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/homeworkOne/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/homeworkOne/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/homeworkOne/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/homeworkOne/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/homeworkOne/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/homeworkOne/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/homeworkOne/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/homeworkOne/merges",
    "archive_url": "https://api.github.com/repos/kpittner/homeworkOne/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/homeworkOne/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/homeworkOne/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/homeworkOne/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/homeworkOne/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/homeworkOne/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/homeworkOne/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/homeworkOne/releases{/id}",
    "created_at": "2015-05-20T13:02:56Z",
    "updated_at": "2015-05-20T15:39:04Z",
    "pushed_at": "2015-05-20T15:39:04Z",
    "git_url": "git://github.com/kpittner/homeworkOne.git",
    "ssh_url": "git@github.com:kpittner/homeworkOne.git",
    "clone_url": "https://github.com/kpittner/homeworkOne.git",
    "svn_url": "https://github.com/kpittner/homeworkOne",
    "homepage": null,
    "size": 8140,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 36777483,
    "name": "javaScriptAssignment",
    "full_name": "kpittner/javaScriptAssignment",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/javaScriptAssignment",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/javaScriptAssignment",
    "forks_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/forks",
    "keys_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/events",
    "assignees_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/merges",
    "archive_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/javaScriptAssignment/releases{/id}",
    "created_at": "2015-06-03T03:22:40Z",
    "updated_at": "2015-06-03T03:24:21Z",
    "pushed_at": "2015-06-03T03:24:21Z",
    "git_url": "git://github.com/kpittner/javaScriptAssignment.git",
    "ssh_url": "git@github.com:kpittner/javaScriptAssignment.git",
    "clone_url": "https://github.com/kpittner/javaScriptAssignment.git",
    "svn_url": "https://github.com/kpittner/javaScriptAssignment",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 36770563,
    "name": "js-functions",
    "full_name": "kpittner/js-functions",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/js-functions",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/js-functions",
    "forks_url": "https://api.github.com/repos/kpittner/js-functions/forks",
    "keys_url": "https://api.github.com/repos/kpittner/js-functions/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/js-functions/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/js-functions/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/js-functions/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/js-functions/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/js-functions/events",
    "assignees_url": "https://api.github.com/repos/kpittner/js-functions/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/js-functions/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/js-functions/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/js-functions/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/js-functions/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/js-functions/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/js-functions/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/js-functions/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/js-functions/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/js-functions/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/js-functions/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/js-functions/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/js-functions/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/js-functions/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/js-functions/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/js-functions/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/js-functions/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/js-functions/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/js-functions/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/js-functions/merges",
    "archive_url": "https://api.github.com/repos/kpittner/js-functions/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/js-functions/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/js-functions/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/js-functions/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/js-functions/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/js-functions/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/js-functions/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/js-functions/releases{/id}",
    "created_at": "2015-06-03T00:49:23Z",
    "updated_at": "2015-06-03T00:53:09Z",
    "pushed_at": "2015-06-03T00:53:09Z",
    "git_url": "git://github.com/kpittner/js-functions.git",
    "ssh_url": "git@github.com:kpittner/js-functions.git",
    "clone_url": "https://github.com/kpittner/js-functions.git",
    "svn_url": "https://github.com/kpittner/js-functions",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 36828267,
    "name": "map-filter",
    "full_name": "kpittner/map-filter",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/map-filter",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/map-filter",
    "forks_url": "https://api.github.com/repos/kpittner/map-filter/forks",
    "keys_url": "https://api.github.com/repos/kpittner/map-filter/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/map-filter/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/map-filter/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/map-filter/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/map-filter/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/map-filter/events",
    "assignees_url": "https://api.github.com/repos/kpittner/map-filter/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/map-filter/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/map-filter/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/map-filter/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/map-filter/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/map-filter/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/map-filter/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/map-filter/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/map-filter/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/map-filter/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/map-filter/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/map-filter/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/map-filter/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/map-filter/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/map-filter/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/map-filter/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/map-filter/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/map-filter/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/map-filter/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/map-filter/merges",
    "archive_url": "https://api.github.com/repos/kpittner/map-filter/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/map-filter/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/map-filter/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/map-filter/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/map-filter/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/map-filter/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/map-filter/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/map-filter/releases{/id}",
    "created_at": "2015-06-03T20:19:54Z",
    "updated_at": "2015-06-03T20:20:52Z",
    "pushed_at": "2015-06-03T20:20:51Z",
    "git_url": "git://github.com/kpittner/map-filter.git",
    "ssh_url": "git@github.com:kpittner/map-filter.git",
    "clone_url": "https://github.com/kpittner/map-filter.git",
    "svn_url": "https://github.com/kpittner/map-filter",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 36680370,
    "name": "peralta",
    "full_name": "kpittner/peralta",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/peralta",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/peralta",
    "forks_url": "https://api.github.com/repos/kpittner/peralta/forks",
    "keys_url": "https://api.github.com/repos/kpittner/peralta/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/peralta/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/peralta/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/peralta/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/peralta/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/peralta/events",
    "assignees_url": "https://api.github.com/repos/kpittner/peralta/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/peralta/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/peralta/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/peralta/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/peralta/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/peralta/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/peralta/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/peralta/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/peralta/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/peralta/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/peralta/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/peralta/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/peralta/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/peralta/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/peralta/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/peralta/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/peralta/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/peralta/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/peralta/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/peralta/merges",
    "archive_url": "https://api.github.com/repos/kpittner/peralta/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/peralta/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/peralta/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/peralta/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/peralta/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/peralta/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/peralta/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/peralta/releases{/id}",
    "created_at": "2015-06-01T18:33:01Z",
    "updated_at": "2015-06-01T18:33:24Z",
    "pushed_at": "2015-06-01T18:33:23Z",
    "git_url": "git://github.com/kpittner/peralta.git",
    "ssh_url": "git@github.com:kpittner/peralta.git",
    "clone_url": "https://github.com/kpittner/peralta.git",
    "svn_url": "https://github.com/kpittner/peralta",
    "homepage": null,
    "size": 3560,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 37076749,
    "name": "photo-album",
    "full_name": "kpittner/photo-album",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/photo-album",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/photo-album",
    "forks_url": "https://api.github.com/repos/kpittner/photo-album/forks",
    "keys_url": "https://api.github.com/repos/kpittner/photo-album/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/photo-album/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/photo-album/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/photo-album/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/photo-album/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/photo-album/events",
    "assignees_url": "https://api.github.com/repos/kpittner/photo-album/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/photo-album/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/photo-album/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/photo-album/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/photo-album/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/photo-album/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/photo-album/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/photo-album/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/photo-album/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/photo-album/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/photo-album/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/photo-album/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/photo-album/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/photo-album/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/photo-album/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/photo-album/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/photo-album/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/photo-album/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/photo-album/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/photo-album/merges",
    "archive_url": "https://api.github.com/repos/kpittner/photo-album/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/photo-album/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/photo-album/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/photo-album/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/photo-album/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/photo-album/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/photo-album/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/photo-album/releases{/id}",
    "created_at": "2015-06-08T15:51:54Z",
    "updated_at": "2015-06-08T18:33:06Z",
    "pushed_at": "2015-06-09T13:10:20Z",
    "git_url": "git://github.com/kpittner/photo-album.git",
    "ssh_url": "git@github.com:kpittner/photo-album.git",
    "clone_url": "https://github.com/kpittner/photo-album.git",
    "svn_url": "https://github.com/kpittner/photo-album",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 36038639,
    "name": "surfandpaddleco",
    "full_name": "kpittner/surfandpaddleco",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/surfandpaddleco",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/surfandpaddleco",
    "forks_url": "https://api.github.com/repos/kpittner/surfandpaddleco/forks",
    "keys_url": "https://api.github.com/repos/kpittner/surfandpaddleco/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/surfandpaddleco/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/surfandpaddleco/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/surfandpaddleco/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/surfandpaddleco/events",
    "assignees_url": "https://api.github.com/repos/kpittner/surfandpaddleco/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/surfandpaddleco/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/surfandpaddleco/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/surfandpaddleco/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/surfandpaddleco/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/surfandpaddleco/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/surfandpaddleco/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/surfandpaddleco/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/surfandpaddleco/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/surfandpaddleco/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/surfandpaddleco/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/surfandpaddleco/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/surfandpaddleco/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/surfandpaddleco/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/surfandpaddleco/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/surfandpaddleco/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/surfandpaddleco/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/surfandpaddleco/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/surfandpaddleco/merges",
    "archive_url": "https://api.github.com/repos/kpittner/surfandpaddleco/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/surfandpaddleco/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/surfandpaddleco/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/surfandpaddleco/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/surfandpaddleco/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/surfandpaddleco/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/surfandpaddleco/releases{/id}",
    "created_at": "2015-05-21T21:38:45Z",
    "updated_at": "2015-05-28T13:53:51Z",
    "pushed_at": "2015-05-28T13:53:51Z",
    "git_url": "git://github.com/kpittner/surfandpaddleco.git",
    "ssh_url": "git@github.com:kpittner/surfandpaddleco.git",
    "clone_url": "https://github.com/kpittner/surfandpaddleco.git",
    "svn_url": "https://github.com/kpittner/surfandpaddleco",
    "homepage": null,
    "size": 2116,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 1,
    "forks": 0,
    "open_issues": 1,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 36872948,
    "name": "theDOM",
    "full_name": "kpittner/theDOM",
    "owner": {
      "login": "kpittner",
      "id": 12478022,
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "html_url": "https://github.com/kpittner",
      "followers_url": "https://api.github.com/users/kpittner/followers",
      "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
      "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
      "organizations_url": "https://api.github.com/users/kpittner/orgs",
      "repos_url": "https://api.github.com/users/kpittner/repos",
      "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kpittner/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/kpittner/theDOM",
    "description": "",
    "fork": false,
    "url": "https://api.github.com/repos/kpittner/theDOM",
    "forks_url": "https://api.github.com/repos/kpittner/theDOM/forks",
    "keys_url": "https://api.github.com/repos/kpittner/theDOM/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/kpittner/theDOM/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/kpittner/theDOM/teams",
    "hooks_url": "https://api.github.com/repos/kpittner/theDOM/hooks",
    "issue_events_url": "https://api.github.com/repos/kpittner/theDOM/issues/events{/number}",
    "events_url": "https://api.github.com/repos/kpittner/theDOM/events",
    "assignees_url": "https://api.github.com/repos/kpittner/theDOM/assignees{/user}",
    "branches_url": "https://api.github.com/repos/kpittner/theDOM/branches{/branch}",
    "tags_url": "https://api.github.com/repos/kpittner/theDOM/tags",
    "blobs_url": "https://api.github.com/repos/kpittner/theDOM/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/kpittner/theDOM/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/kpittner/theDOM/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/kpittner/theDOM/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/kpittner/theDOM/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/kpittner/theDOM/languages",
    "stargazers_url": "https://api.github.com/repos/kpittner/theDOM/stargazers",
    "contributors_url": "https://api.github.com/repos/kpittner/theDOM/contributors",
    "subscribers_url": "https://api.github.com/repos/kpittner/theDOM/subscribers",
    "subscription_url": "https://api.github.com/repos/kpittner/theDOM/subscription",
    "commits_url": "https://api.github.com/repos/kpittner/theDOM/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/kpittner/theDOM/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/kpittner/theDOM/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/kpittner/theDOM/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/kpittner/theDOM/contents/{+path}",
    "compare_url": "https://api.github.com/repos/kpittner/theDOM/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/kpittner/theDOM/merges",
    "archive_url": "https://api.github.com/repos/kpittner/theDOM/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/kpittner/theDOM/downloads",
    "issues_url": "https://api.github.com/repos/kpittner/theDOM/issues{/number}",
    "pulls_url": "https://api.github.com/repos/kpittner/theDOM/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/kpittner/theDOM/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/kpittner/theDOM/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/kpittner/theDOM/labels{/name}",
    "releases_url": "https://api.github.com/repos/kpittner/theDOM/releases{/id}",
    "created_at": "2015-06-04T13:48:24Z",
    "updated_at": "2015-06-04T13:49:06Z",
    "pushed_at": "2015-06-04T13:49:05Z",
    "git_url": "git://github.com/kpittner/theDOM.git",
    "ssh_url": "git@github.com:kpittner/theDOM.git",
    "clone_url": "https://github.com/kpittner/theDOM.git",
    "svn_url": "https://github.com/kpittner/theDOM",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
]


var myEvents = [
  {
    "id": "2876232090",
    "type": "PushEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 37076749,
      "name": "kpittner/photo-album",
      "url": "https://api.github.com/repos/kpittner/photo-album"
    },
    "payload": {
      "push_id": 689529379,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "1bc8e5b20055d117aac5ee94522cf20ce70b99db",
      "before": "f88e2df278ae539f6ffe269d138562549885bac9",
      "commits": [
        {
          "sha": "1bc8e5b20055d117aac5ee94522cf20ce70b99db",
          "author": {
            "email": "KelseyJade@Kelseys-MacBook-Air.local",
            "name": "Kelsey Pittner"
          },
          "message": "Some more",
          "distinct": true,
          "url": "https://api.github.com/repos/kpittner/photo-album/commits/1bc8e5b20055d117aac5ee94522cf20ce70b99db"
        }
      ]
    },
    "public": true,
    "created_at": "2015-06-09T13:10:20Z"
  },
  {
    "id": "2874121895",
    "type": "PushEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 37076749,
      "name": "kpittner/photo-album",
      "url": "https://api.github.com/repos/kpittner/photo-album"
    },
    "payload": {
      "push_id": 688766561,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "f88e2df278ae539f6ffe269d138562549885bac9",
      "before": "fb88e1b981f9d3bab09fe7fc6d5cf336437024b8",
      "commits": [
        {
          "sha": "f88e2df278ae539f6ffe269d138562549885bac9",
          "author": {
            "email": "KelseyJade@Kelseys-MacBook-Air.local",
            "name": "Kelsey Pittner"
          },
          "message": "more",
          "distinct": true,
          "url": "https://api.github.com/repos/kpittner/photo-album/commits/f88e2df278ae539f6ffe269d138562549885bac9"
        }
      ]
    },
    "public": true,
    "created_at": "2015-06-08T20:44:55Z"
  },
  {
    "id": "2873715196",
    "type": "PushEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 37076749,
      "name": "kpittner/photo-album",
      "url": "https://api.github.com/repos/kpittner/photo-album"
    },
    "payload": {
      "push_id": 688623124,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "fb88e1b981f9d3bab09fe7fc6d5cf336437024b8",
      "before": "ea0f695f085b790f4f0ccd1bb5ca680464449940",
      "commits": [
        {
          "sha": "fb88e1b981f9d3bab09fe7fc6d5cf336437024b8",
          "author": {
            "email": "KelseyJade@Kelseys-MacBook-Air.local",
            "name": "Kelsey Pittner"
          },
          "message": "Updated, but not done yet",
          "distinct": true,
          "url": "https://api.github.com/repos/kpittner/photo-album/commits/fb88e1b981f9d3bab09fe7fc6d5cf336437024b8"
        }
      ]
    },
    "public": true,
    "created_at": "2015-06-08T18:33:06Z"
  },
  {
    "id": "2873210219",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 37076749,
      "name": "kpittner/photo-album",
      "url": "https://api.github.com/repos/kpittner/photo-album"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-08T15:53:26Z"
  },
  {
    "id": "2873204797",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 37076749,
      "name": "kpittner/photo-album",
      "url": "https://api.github.com/repos/kpittner/photo-album"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-08T15:51:54Z"
  },
  {
    "id": "2863699248",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36872948,
      "name": "kpittner/theDOM",
      "url": "https://api.github.com/repos/kpittner/theDOM"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-04T13:49:05Z"
  },
  {
    "id": "2863697124",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36872948,
      "name": "kpittner/theDOM",
      "url": "https://api.github.com/repos/kpittner/theDOM"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-04T13:48:27Z"
  },
  {
    "id": "2861365415",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36828267,
      "name": "kpittner/map-filter",
      "url": "https://api.github.com/repos/kpittner/map-filter"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-03T20:20:51Z"
  },
  {
    "id": "2861362166",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36828267,
      "name": "kpittner/map-filter",
      "url": "https://api.github.com/repos/kpittner/map-filter"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-03T20:19:54Z"
  },
  {
    "id": "2858525666",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36777483,
      "name": "kpittner/javaScriptAssignment",
      "url": "https://api.github.com/repos/kpittner/javaScriptAssignment"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-03T03:24:21Z"
  },
  {
    "id": "2858523211",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36777483,
      "name": "kpittner/javaScriptAssignment",
      "url": "https://api.github.com/repos/kpittner/javaScriptAssignment"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-03T03:22:40Z"
  },
  {
    "id": "2858277013",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36770563,
      "name": "kpittner/js-functions",
      "url": "https://api.github.com/repos/kpittner/js-functions"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-03T00:53:09Z"
  },
  {
    "id": "2858270089",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36770563,
      "name": "kpittner/js-functions",
      "url": "https://api.github.com/repos/kpittner/js-functions"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-03T00:49:23Z"
  },
  {
    "id": "2853434911",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36680370,
      "name": "kpittner/peralta",
      "url": "https://api.github.com/repos/kpittner/peralta"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-01T18:33:23Z"
  },
  {
    "id": "2853433690",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36680370,
      "name": "kpittner/peralta",
      "url": "https://api.github.com/repos/kpittner/peralta"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-06-01T18:33:01Z"
  },
  {
    "id": "2843201131",
    "type": "PushEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36038639,
      "name": "kpittner/surfandpaddleco",
      "url": "https://api.github.com/repos/kpittner/surfandpaddleco"
    },
    "payload": {
      "push_id": 677743043,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "d26eba8966f4d296a10bb367ef3165823f008f19",
      "before": "da8a8e401f41ab973ebeb1dc44a73907ecdd144d",
      "commits": [
        {
          "sha": "d26eba8966f4d296a10bb367ef3165823f008f19",
          "author": {
            "email": "KelseyJade@Kelseys-MacBook-Air.local",
            "name": "Kelsey Pittner"
          },
          "message": "repositioned elements",
          "distinct": true,
          "url": "https://api.github.com/repos/kpittner/surfandpaddleco/commits/d26eba8966f4d296a10bb367ef3165823f008f19"
        }
      ]
    },
    "public": true,
    "created_at": "2015-05-28T13:53:51Z"
  },
  {
    "id": "2843198077",
    "type": "PushEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36038639,
      "name": "kpittner/surfandpaddleco",
      "url": "https://api.github.com/repos/kpittner/surfandpaddleco"
    },
    "payload": {
      "push_id": 677741891,
      "size": 1,
      "distinct_size": 1,
      "ref": "refs/heads/master",
      "head": "da8a8e401f41ab973ebeb1dc44a73907ecdd144d",
      "before": "4dd23fb558d18016285b408468999bc551439f15",
      "commits": [
        {
          "sha": "da8a8e401f41ab973ebeb1dc44a73907ecdd144d",
          "author": {
            "email": "KelseyJade@Kelseys-MacBook-Air.local",
            "name": "Kelsey Pittner"
          },
          "message": "Some errors have been fixed",
          "distinct": true,
          "url": "https://api.github.com/repos/kpittner/surfandpaddleco/commits/da8a8e401f41ab973ebeb1dc44a73907ecdd144d"
        }
      ]
    },
    "public": true,
    "created_at": "2015-05-28T13:52:58Z"
  },
  {
    "id": "2826532988",
    "type": "IssueCommentEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36038639,
      "name": "kpittner/surfandpaddleco",
      "url": "https://api.github.com/repos/kpittner/surfandpaddleco"
    },
    "payload": {
      "action": "created",
      "issue": {
        "url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/1",
        "labels_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/1/labels{/name}",
        "comments_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/1/comments",
        "events_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/1/events",
        "html_url": "https://github.com/kpittner/surfandpaddleco/issues/1",
        "id": 79178726,
        "number": 1,
        "title": "here's a copy and paste of my stylesheet that fixed it.",
        "user": {
          "login": "dominathan",
          "id": 6124206,
          "avatar_url": "https://avatars.githubusercontent.com/u/6124206?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/dominathan",
          "html_url": "https://github.com/dominathan",
          "followers_url": "https://api.github.com/users/dominathan/followers",
          "following_url": "https://api.github.com/users/dominathan/following{/other_user}",
          "gists_url": "https://api.github.com/users/dominathan/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/dominathan/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/dominathan/subscriptions",
          "organizations_url": "https://api.github.com/users/dominathan/orgs",
          "repos_url": "https://api.github.com/users/dominathan/repos",
          "events_url": "https://api.github.com/users/dominathan/events{/privacy}",
          "received_events_url": "https://api.github.com/users/dominathan/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [

        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "milestone": null,
        "comments": 1,
        "created_at": "2015-05-21T22:01:12Z",
        "updated_at": "2015-05-22T03:37:53Z",
        "closed_at": null,
        "body": "The main difference are these three.  \r\n```\r\nfooter ul {\r\n  padding: 0;\r\n  margin: 0;\r\n}\r\n\r\n.footer>li {\r\n  position: relative;\r\n  display: inline-block;\r\n  width: 357px;\r\n  height: 354px;\r\n  margin: 0;\r\n}\r\n\r\n.footer img {\r\n  width: 358px;\r\n  height: 350px;\r\n}\r\n```\r\nThe footer ul had a built in padding and margin that wasn't being cancelled out by the normalize.css because it wasn't referenced.  We can go over it more tomorrow.  Sorry it took me awhile to catch.  \r\n\r\n```\r\n#container {\r\n  width: 100%;\r\n  height: 100%;\r\n  margin: 0;\r\n  padding: 0;\r\n}\r\n\r\nbody {\r\n  margin: 0;\r\n  overflow-x: hidden;\r\n}\r\n\r\nheader img {\r\n  top: 0;\r\n  left: 0;\r\n}\r\n\r\n#text {\r\n  color: white;\r\n  font-style: normal;\r\n  font-size: 75px;\r\n  font-weight: normal;\r\n  font-family: sans-serif;\r\n  position: absolute;\r\n  margin: 0;\r\n  top: 30%;\r\n  left: 25%;\r\n}\r\n\r\n#heading {\r\n  color: black;\r\n  font-size: 15px;\r\n  font-family: sans-serif;\r\n  position: absolute;\r\n  margin: 20px;\r\n  padding-left: 1100px;\r\n  top: 0;\r\n}\r\n\r\n#heading li:hover {\r\n  color: grey;\r\n}\r\n\r\n#leftheading {\r\n  color: black;\r\n  list-style-type: none;\r\n  font-size: 15px;\r\n  font-family: sans-serif;\r\n  position: absolute;\r\n  margin: 15px;\r\n  padding-left: 70px;\r\n  top: 0;\r\n}\r\n\r\n#leftheading img{\r\n  padding-left: 10px;\r\n  height: 30px;\r\n  width: 30px;\r\n}\r\n\r\n#middleheading {\r\n  color: black;\r\n  display: inline-block;\r\n  font-weight: lighter;\r\n  list-style-type: none;\r\n  font-size: 17px;\r\n  font-family: sans-serif;\r\n  position: absolute;\r\n  margin: 0;\r\n  top: 43%;\r\n  left: 42%;\r\n}\r\n\r\n#leftheading ul {\r\n  display: inline-block;\r\n  margin: 0;\r\n  padding: 0;\r\n  float: left;\r\n}\r\n\r\nheader ul li {\r\n  display: inline-block;\r\n  margin: 0;\r\n  padding: 10px;\r\n  float: right;\r\n}\r\n\r\n#blog {\r\n  float: left;\r\n}\r\n\r\nsection h5 {\r\n  padding-left: 30px;\r\n  display: inline;\r\n}\r\n\r\nsection h1 {\r\n  font-size: 50px;\r\n  padding-left: 100px;\r\n}\r\n\r\nsection {\r\n  float: left;\r\n  width: 65%;\r\n  margin: 0;\r\n}\r\n\r\nsection img {\r\n  width: 20px;\r\n  height: 20px;\r\n  padding-left: 100px;\r\n  float: left;\r\n}\r\n\r\nsection p {\r\n  margin-left: 100px;\r\n  margin-right: 200px;\r\n}\r\n\r\n.woah {\r\n  font-size: 30px;\r\n  border-left: 2px;\r\n  border-top: 0;\r\n  border-right: 0;\r\n  border-bottom: 0;\r\n  border-style: solid;\r\n  border-color: grey;\r\n  padding: 8px;\r\n  font-family: sans-serif;\r\n  font-weight: lighter;\r\n}\r\n\r\n.media img {\r\n  width: 150px;\r\n  height: 30px;\r\n  padding-left: 0;\r\n  bottom: 90%;\r\n  margin: 3px;\r\n}\r\n\r\naside {\r\n  float: left;\r\n  margin: 0;\r\n  width: 33%;\r\n}\r\n\r\naside img {\r\n  width: 80px;\r\n  height: 80px;\r\n  padding-left: 125px;\r\n  top: 80%;\r\n}\r\n\r\n.picture2 img {\r\n  width: 350px;\r\n  height: 400px;\r\n  padding-left: 0;\r\n  top: 50%;\r\n}\r\n\r\n.picture2 p {\r\n  width: 400px;\r\n}\r\n\r\n.picture2 h6 a {\r\n  padding-left: 280px;\r\n  color: grey;\r\n}\r\n\r\naside h4 {\r\n  padding-left: 120px;\r\n  color: #0080FF;\r\n  font-weight: lighter;\r\n  font-family: sans-serif;\r\n}\r\n\r\naside h5 {\r\n  padding-left: 70px;\r\n  color: #D8D8D8;\r\n  font-weight: lighter;\r\n  font-family: sans-serif;\r\n}\r\n\r\n.popular {\r\n  padding-left: 350px;\r\n  font-family: sans-serif;\r\n  font-weight: lighter;\r\n  font-size: 30px;\r\n  margin: 0;\r\n  padding-top: 20px;\r\n  width: 100%;\r\n  height: 150px;\r\n  border-top: 2px;\r\n  border-style: solid;\r\n  border-width: thin;\r\n  border-color: #D8D8D8;\r\n  border-left: 0;\r\n  border-bottom: 0;\r\n  border-right: 0;\r\n  clear: both;\r\n}\r\n\r\n.popular h1{\r\n  margin: 0;\r\n  padding-left: 130px;\r\n}\r\n\r\n.popular:after {\r\n  content: '';\r\n  clear:both;\r\n  }\r\n\r\n/*.footer ul li {\r\n  display: inline-block;\r\n  margin: 0;\r\n  padding: 0;\r\n  color: grey;\r\n}*/\r\n\r\n.footer2 {\r\n  background-color: #224681;\r\n  border-color: #224681;\r\n  height: 75px;\r\n  border-style: solid;\r\n  clear: both;\r\n  margin-top: -5px;\r\n}\r\n\r\n.footer2 p {\r\n  display: inline;\r\n  width: 50px;\r\n  height: 7px;\r\n  padding-left: 15px;\r\n}\r\n\r\n.footer2 ul li {\r\n  color: grey;\r\n  display: inline-block;\r\n  list-style-type: none;\r\n  height: 15px;\r\n  float: right;\r\n  padding-right: 0;\r\n  margin: 0;\r\n}\r\n\r\n.footer2 li:hover {\r\n  background-color: white;\r\n}\r\n\r\n.footer2 img {\r\n  width: 50px;\r\n  height: 50px;\r\n  padding-left: 100px;\r\n  padding-top: 10px;\r\n  float: left;\r\n}\r\n\r\nfooter {\r\n  clear: both;\r\n}\r\n\r\nfooter ul {\r\n  padding: 0;\r\n  margin: 0;\r\n}\r\n\r\n.footer>li {\r\n  position: relative;\r\n  display: inline-block;\r\n  width: 357px;\r\n  height: 354px;\r\n  margin: 0;\r\n}\r\n\r\n.footer img {\r\n  width: 358px;\r\n  height: 350px;\r\n}\r\n\r\n/*.footer img {\r\n  width: 350px;\r\n  height: 358px;\r\n  display: inline-block;\r\n  float: left;\r\n}*/\r\n\r\n.footer li:hover {\r\n  opacity: 0.4;\r\n}\r\n\r\n.footer > li h3 {\r\n  position: absolute;\r\n  bottom: 5px;\r\n  left: 5px;\r\n  color: white;\r\n}\r\n```"
      },
      "comment": {
        "url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/comments/104493692",
        "html_url": "https://github.com/kpittner/surfandpaddleco/issues/1#issuecomment-104493692",
        "issue_url": "https://api.github.com/repos/kpittner/surfandpaddleco/issues/1",
        "id": 104493692,
        "user": {
          "login": "kpittner",
          "id": 12478022,
          "avatar_url": "https://avatars.githubusercontent.com/u/12478022?v=3",
          "gravatar_id": "",
          "url": "https://api.github.com/users/kpittner",
          "html_url": "https://github.com/kpittner",
          "followers_url": "https://api.github.com/users/kpittner/followers",
          "following_url": "https://api.github.com/users/kpittner/following{/other_user}",
          "gists_url": "https://api.github.com/users/kpittner/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/kpittner/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/kpittner/subscriptions",
          "organizations_url": "https://api.github.com/users/kpittner/orgs",
          "repos_url": "https://api.github.com/users/kpittner/repos",
          "events_url": "https://api.github.com/users/kpittner/events{/privacy}",
          "received_events_url": "https://api.github.com/users/kpittner/received_events",
          "type": "User",
          "site_admin": false
        },
        "created_at": "2015-05-22T03:37:53Z",
        "updated_at": "2015-05-22T03:37:53Z",
        "body": "Sounds good. Thanks for looking into that for me. I appreciate it!\n\nKelsey J Pittner\nManager/Event Coordinator\nPaolo's Gelato - Charleston/Atlanta\nCitadel Class of 2014\nL Co./3BS\nOn May 21, 2015 6:01 PM, \"Nathan Hall\" <notifications@github.com> wrote:\n\n> The main difference are these three. The footer ul had a built in padding\n> and margin that wasn't being cancelled out by the normalize.css because it\n> wasn't referenced. We can go over it more tomorrow. Sorry it took me awhile\n> to catch.\n>\n> #container {\n>   width: 100%;\n>   height: 100%;\n>   margin: 0;\n>   padding: 0;\n> }\n>\n> body {\n>   margin: 0;\n>   overflow-x: hidden;\n> }\n>\n> header img {\n>   top: 0;\n>   left: 0;\n> }\n>\n> #text {\n>   color: white;\n>   font-style: normal;\n>   font-size: 75px;\n>   font-weight: normal;\n>   font-family: sans-serif;\n>   position: absolute;\n>   margin: 0;\n>   top: 30%;\n>   left: 25%;\n> }\n>\n> #heading {\n>   color: black;\n>   font-size: 15px;\n>   font-family: sans-serif;\n>   position: absolute;\n>   margin: 20px;\n>   padding-left: 1100px;\n>   top: 0;\n> }\n>\n> #heading li:hover {\n>   color: grey;\n> }\n>\n> #leftheading {\n>   color: black;\n>   list-style-type: none;\n>   font-size: 15px;\n>   font-family: sans-serif;\n>   position: absolute;\n>   margin: 15px;\n>   padding-left: 70px;\n>   top: 0;\n> }\n>\n> #leftheading img{\n>   padding-left: 10px;\n>   height: 30px;\n>   width: 30px;\n> }\n>\n> #middleheading {\n>   color: black;\n>   display: inline-block;\n>   font-weight: lighter;\n>   list-style-type: none;\n>   font-size: 17px;\n>   font-family: sans-serif;\n>   position: absolute;\n>   margin: 0;\n>   top: 43%;\n>   left: 42%;\n> }\n>\n> #leftheading ul {\n>   display: inline-block;\n>   margin: 0;\n>   padding: 0;\n>   float: left;\n> }\n>\n> header ul li {\n>   display: inline-block;\n>   margin: 0;\n>   padding: 10px;\n>   float: right;\n> }\n>\n> #blog {\n>   float: left;\n> }\n>\n> section h5 {\n>   padding-left: 30px;\n>   display: inline;\n> }\n>\n> section h1 {\n>   font-size: 50px;\n>   padding-left: 100px;\n> }\n>\n> section {\n>   float: left;\n>   width: 65%;\n>   margin: 0;\n> }\n>\n> section img {\n>   width: 20px;\n>   height: 20px;\n>   padding-left: 100px;\n>   float: left;\n> }\n>\n> section p {\n>   margin-left: 100px;\n>   margin-right: 200px;\n> }\n>\n> .woah {\n>   font-size: 30px;\n>   border-left: 2px;\n>   border-top: 0;\n>   border-right: 0;\n>   border-bottom: 0;\n>   border-style: solid;\n>   border-color: grey;\n>   padding: 8px;\n>   font-family: sans-serif;\n>   font-weight: lighter;\n> }\n>\n> .media img {\n>   width: 150px;\n>   height: 30px;\n>   padding-left: 0;\n>   bottom: 90%;\n>   margin: 3px;\n> }\n>\n> aside {\n>   float: left;\n>   margin: 0;\n>   width: 33%;\n> }\n>\n> aside img {\n>   width: 80px;\n>   height: 80px;\n>   padding-left: 125px;\n>   top: 80%;\n> }\n>\n> .picture2 img {\n>   width: 350px;\n>   height: 400px;\n>   padding-left: 0;\n>   top: 50%;\n> }\n>\n> .picture2 p {\n>   width: 400px;\n> }\n>\n> .picture2 h6 a {\n>   padding-left: 280px;\n>   color: grey;\n> }\n>\n> aside h4 {\n>   padding-left: 120px;\n>   color: #0080FF;\n>   font-weight: lighter;\n>   font-family: sans-serif;\n> }\n>\n> aside h5 {\n>   padding-left: 70px;\n>   color: #D8D8D8;\n>   font-weight: lighter;\n>   font-family: sans-serif;\n> }\n>\n> .popular {\n>   padding-left: 350px;\n>   font-family: sans-serif;\n>   font-weight: lighter;\n>   font-size: 30px;\n>   margin: 0;\n>   padding-top: 20px;\n>   width: 100%;\n>   height: 150px;\n>   border-top: 2px;\n>   border-style: solid;\n>   border-width: thin;\n>   border-color: #D8D8D8;\n>   border-left: 0;\n>   border-bottom: 0;\n>   border-right: 0;\n>   clear: both;\n> }\n>\n> .popular h1{\n>   margin: 0;\n>   padding-left: 130px;\n> }\n>\n> .popular:after {\n>   content: '';\n>   clear:both;\n>   }\n>\n> /*.footer ul li {\n>   display: inline-block;\n>   margin: 0;\n>   padding: 0;\n>   color: grey;\n> }*/\n>\n> .footer2 {\n>   background-color: #224681;\n>   border-color: #224681;\n>   height: 75px;\n>   border-style: solid;\n>   clear: both;\n>   margin-top: -5px;\n> }\n>\n> .footer2 p {\n>   display: inline;\n>   width: 50px;\n>   height: 7px;\n>   padding-left: 15px;\n> }\n>\n> .footer2 ul li {\n>   color: grey;\n>   display: inline-block;\n>   list-style-type: none;\n>   height: 15px;\n>   float: right;\n>   padding-right: 0;\n>   margin: 0;\n> }\n>\n> .footer2 li:hover {\n>   background-color: white;\n> }\n>\n> .footer2 img {\n>   width: 50px;\n>   height: 50px;\n>   padding-left: 100px;\n>   padding-top: 10px;\n>   float: left;\n> }\n>\n> footer {\n>   clear: both;\n> }\n>\n> footer ul {\n>   padding: 0;\n>   margin: 0;\n> }\n>\n> .footer>li {\n>   position: relative;\n>   display: inline-block;\n>   width: 357px;\n>   height: 354px;\n>   margin: 0;\n> }\n>\n> .footer img {\n>   width: 358px;\n>   height: 350px;\n> }\n>\n> /*.footer img {\n>   width: 350px;\n>   height: 358px;\n>   display: inline-block;\n>   float: left;\n> }*/\n>\n> .footer li:hover {\n>   opacity: 0.4;\n> }\n>\n> .footer > li h3 {\n>   position: absolute;\n>   bottom: 5px;\n>   left: 5px;\n>   color: white;\n> }\n>\n> —\n> Reply to this email directly or view it on GitHub\n> <https://github.com/kpittner/surfandpaddleco/issues/1>.\n>\n"
      }
    },
    "public": true,
    "created_at": "2015-05-22T03:37:54Z"
  },
  {
    "id": "2825854274",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36038639,
      "name": "kpittner/surfandpaddleco",
      "url": "https://api.github.com/repos/kpittner/surfandpaddleco"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-21T21:38:59Z"
  },
  {
    "id": "2825853565",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 36038639,
      "name": "kpittner/surfandpaddleco",
      "url": "https://api.github.com/repos/kpittner/surfandpaddleco"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-21T21:38:45Z"
  },
  {
    "id": "2820940514",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 35948140,
      "name": "kpittner/homeworkOne",
      "url": "https://api.github.com/repos/kpittner/homeworkOne"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-20T15:39:04Z"
  },
  {
    "id": "2820376634",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 35948140,
      "name": "kpittner/homeworkOne",
      "url": "https://api.github.com/repos/kpittner/homeworkOne"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-20T13:02:56Z"
  },
  {
    "id": "2820364957",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 35947930,
      "name": "kpittner/firstDemo",
      "url": "https://api.github.com/repos/kpittner/firstDemo"
    },
    "payload": {
      "ref": "master",
      "ref_type": "branch",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-20T12:59:09Z"
  },
  {
    "id": "2820364100",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 35947930,
      "name": "kpittner/firstDemo",
      "url": "https://api.github.com/repos/kpittner/firstDemo"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-20T12:58:53Z"
  },
  {
    "id": "2817313330",
    "type": "CreateEvent",
    "actor": {
      "id": 12478022,
      "login": "kpittner",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kpittner",
      "avatar_url": "https://avatars.githubusercontent.com/u/12478022?"
    },
    "repo": {
      "id": 35892986,
      "name": "TIY-Charleston-Front-End-May2015/firstDemo",
      "url": "https://api.github.com/repos/TIY-Charleston-Front-End-May2015/firstDemo"
    },
    "payload": {
      "ref": null,
      "ref_type": "repository",
      "master_branch": "master",
      "description": "",
      "pusher_type": "user"
    },
    "public": true,
    "created_at": "2015-05-19T16:03:31Z",
    "org": {
      "id": 12236563,
      "login": "TIY-Charleston-Front-End-May2015",
      "gravatar_id": "",
      "url": "https://api.github.com/orgs/TIY-Charleston-Front-End-May2015",
      "avatar_url": "https://avatars.githubusercontent.com/u/12236563?"
    }
  }
]

var myOrgs = [

]
